repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.6
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.6.2
  hooks:
    - id: uv-lock
    - id: uv-export
      args: [--no-dev, --frozen, -o, requirements.txt]
