[tool.poetry]
name = "skagit-bmc-registration"
version = "0.1.0"
description = "A site to help with registration for the Skagit BMC."
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.8.6"
django = "^3.1.3"
django-localflavor = "^3.0.1"
django-phonenumber-field = {extras = ["phonenumberslite"], version = "^5.0.0"}
django-bulma = "^0.8.1"
djangorestframework = "^3.12.2"
django-extensions = "^3.1.0"
stripe = "^2.55.1"
whitenoise = "^5.2.0"
dj-database-url = "^0.5.0"
gunicorn = "^20.0.4"
psycopg2-binary = "^2.8.6"

[tool.poetry.dev-dependencies]
pytest = "^6.1.2"
pre-commit = "^2.9.0"
pytest-django = "^4.1.0"
model_bakery = "^1.2.1"
isort = "^5.6.4"
pytest-freezegun = "^0.4.2"

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "SkagitRegistration.settings"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

