[tool.poetry]
name = "skagit-bmc-registration"
version = "0.1.0"
description = "A site to help with registration for the Skagit BMC."
authors = ["Raymond DeVries"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.11.6"
django = "^4.0"
django-localflavor = "^3.1.0"
django-phonenumber-field = {extras = ["phonenumberslite"], version = "^7.0.0"}
django-bulma = "^0.8.3"
djangorestframework = "^3.14.0"
django-extensions = "^3.2.1"
stripe = "^4.2.0"
whitenoise = "^6.2.0"
dj-database-url = "^1.0.0"
gunicorn = "^20.1.0"
sentry-sdk = "^1.9.10"
psycopg2 = "^2.9.4"

[tool.poetry.dev-dependencies]
pytest = "^7.1.3"
pre-commit = "^2.20.0"
pytest-django = "^4.5.2"
model_bakery = "^1.8.0"
isort = "^5.10.1"
pytest-freezegun = "^0.4.2"
Faker = "^15.1.1"

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "SkagitRegistration.settings"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

