[tool.poetry]
name = "skagit-bmc-registration"
version = "0.1.0"
description = "A site to help with registration for the Skagit BMC."
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.8"
django = "^3.1.3"
django-localflavor = "^3.0.1"
django-phonenumber-field = {extras = ["phonenumberslite"], version = "^5.0.0"}
django-bulma = "^0.8.1"

[tool.poetry.dev-dependencies]
pytest = "^6.1.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
