# Generated by Django 3.1.3 on 2020-11-26 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="classtype",
            name="visible",
            field=models.BooleanField(default=True),
        ),
    ]
