# Generated by Django 3.1.5 on 2021-01-06 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationform",
            name="pronouns",
            field=models.CharField(default="He/him", max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="coursebought",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="registration.course"
            ),
        ),
        migrations.AlterField(
            model_name="coursebought",
            name="payment_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="registration.paymentrecord",
            ),
        ),
    ]
