# Generated by Django 3.1.3 on 2020-11-25 19:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("registration", "0002_skagitclass_skagitclassdates"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BMCRegistration",
            new_name="RegistrationForm",
        ),
    ]
