# Generated by Django 3.1.5 on 2021-01-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0002_auto_20210106_0549"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrationform",
            name="pronouns",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
