# Generated by Django 3.1.3 on 2020-11-25 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0002_auto_20201125_2307"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SkagitClassDates",
            new_name="SkagitClassDate",
        ),
    ]
