# Generated by Django 3.1.3 on 2020-11-26 08:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("registration", "0002_classtype_visible"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SkagitClass",
            new_name="Course",
        ),
        migrations.RenameModel(
            old_name="SkagitClassDate",
            new_name="CourseDate",
        ),
        migrations.RenameModel(
            old_name="ClassType",
            new_name="CourseType",
        ),
        migrations.AlterModelOptions(
            name="course",
            options={},
        ),
    ]
