# Generated by Django 3.2.10 on 2021-12-24 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0002_registrationsettings_refund_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursebought",
            name="product_id",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
