# Generated by Django 3.1.3 on 2020-12-30 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0002_coursetype_abbreviation"),
    ]

    operations = [
        migrations.CreateModel(
            name="EarlySignupEmail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="RegistrationSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("early_registration_open", models.DateTimeField()),
                ("early_signup_code", models.CharField(max_length=15)),
                ("registration_open", models.DateTimeField()),
                ("registration_close", models.DateTimeField()),
            ],
        ),
    ]
