# Generated by Django 3.2.9 on 2021-11-26 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0002_manual_add_instructor_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentrecord",
            name="payment_id",
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="checkout_session_id",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="payment_intent_id",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
