# Generated by Django 3.1.5 on 2021-01-07 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0003_auto_20210106_0553"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registrationform",
            name="allergy_conditions",
        ),
        migrations.RemoveField(
            model_name="registrationform",
            name="medical_conditions",
        ),
        migrations.RemoveField(
            model_name="registrationform",
            name="medications",
        ),
        migrations.AlterField(
            model_name="registrationform",
            name="gender",
            field=models.CharField(
                choices=[
                    ("M", "Male"),
                    ("F", "Female"),
                    ("N", "Non-Binary"),
                    ("U", "Does not wish to identify"),
                ],
                max_length=1,
            ),
        ),
        migrations.CreateModel(
            name="GearItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=300)),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="registration.coursetype",
                    ),
                ),
            ],
        ),
    ]
