# Generated by Django 3.2.10 on 2021-12-25 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0003_coursebought_product_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursebought",
            name="price_id",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
