# Generated by Django 3.2.10 on 2021-12-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0004_coursebought_price_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationsettings",
            name="cancellation_fee",
            field=models.PositiveIntegerField(default=2500),
            preserve_default=False,
        ),
    ]
