# Generated by Django 3.1.3 on 2020-11-27 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0004_auto_20201126_2130"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coursedate",
            old_name="skagit_class",
            new_name="course",
        ),
    ]
