# Generated by Django 3.1.3 on 2020-12-31 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0004_auto_20201231_2025"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="wait_list",
        ),
    ]
