# Generated by Django 3.1.3 on 2021-01-01 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0005_remove_course_wait_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="number_of_courses",
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
