# Generated by Django 4.1.2 on 2022-11-27 00:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0006_alter_coursebought_course"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gearitem",
            options={"ordering": ["item", "pk"]},
        ),
    ]
