# Generated by Django 3.2.10 on 2021-12-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0007_waitlistinvoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="stripe_customer_id",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
