# Generated by Django 4.1.2 on 2022-12-19 03:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0007_alter_gearitem_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationform",
            name="skagit_county_resident",
            field=models.BooleanField(default=False),
        ),
    ]
