# Generated by Django 5.1.6 on 2026-01-04 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0008_registrationform_skagit_county_resident"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationsettings",
            name="refund_cutoff",
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 20, 0, 0)),
            preserve_default=False,
        ),
    ]
