name: Publish Docker image and deploy
on:
  push:
    branches: 
      - production
jobs:
  push_to_registry_and_deploy:
    name: Push Docker image to GitHub Packages and deploy to server
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout code
      uses: actions/checkout@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to Github Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io 
        username: ${{ github.repository_owner }}
        password: ${{ secrets.PAT }}
    -
      name: Build and push backend
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./lambda.Dockerfile
        pull: true
        push: true
        tags: ghcr.io/raymond-devries/skagit-bmc-registration-backend:latest
    -
      uses: marceloprado/has-changed-path@v1
      name: Check if nginx has changed
      id: nginx-changed
      with:
        paths: nginx
    -
      name: Build and push nginx
      if: steps.nginx-changed.outputs.changed == 'true'
      uses: docker/build-push-action@v2
      with:
        context: ./nginx
        file: ./nginx/lambda.Dockerfile
        pull: true
        push: true
        tags: ghcr.io/raymond-devries/skagit-bmc-registration-nginx:latest
    -
      name: Deploy on server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_KEY }}
        script: |
          docker-compose pull web
          docker-compose pull nginx
          docker-compose up -d
